### ISSUE TITLE
Stuck at mapping process.

### ISSUE THREAD

**Issue by xAdamQ** [Lab-of-AI-and-Robotics/GS_ICP_SLAM#8]
Hi, Thank you for the great work!

When I try to run replica example, I the terminal gets stuck with this here:
```
bash replica.sh
run room0
100%|█████████| 2000/2000 [00:33<00:00, 59.88it/s]
Waiting for mapping process to be prepared
  0%| | 0/2000 [00:00<?, ?it/s]
```

Also, how should I view the map being created in realtime, via SIBR remote viewer? Does it need an address to connect to? Can you please provide more info about this (maybe just a link to an existing resource about this).

**Comment by Riboha** [comment]
Thanks for your attention to our work!
This issue is the same as the issue raised in #2, and it seems to be caused by environmental differences.
On ubuntu 20.04, GS-ICP SLAM runs well, but goes wrong on ubuntu 22.04.

Currently, I'm making dockerfile containing GS-ICP SLAM, including SIBR remote viewer.
